CREATE
--DROP
DATABASE DA_NMCNPM
GO

USE DA_NMCNPM 
GO

CREATE
--DROP
TABLE NHANVIEN (
	NV_MA INT IDENTITY(1,1) PRIMARY KEY,
	NV_TEN NVARCHAR(100) NOT NULL,
	NV_GIOTINH NVARCHAR(10) NOT NULL,
	NV_SDT NVARCHAR(20) NOT NULL,
	NV_LUONG_GIO MONEY,
);
GO

CREATE
--DROP
TABLE CALAMVIEC (
	CLV_MA INT IDENTITY(1,1) PRIMARY KEY,
	CLV_NGAY DATE,
	CLV_GIOBATDAU TIME,
	CLV_GIOKETTHUC TIME
)
GO

CREATE 
--DROP
TABLE PHANCONGLAMVIEC(
	CLV_MA INT,
	NV_MA INT,
	CONSTRAINT PK_PHANCONGLAMVIEC PRIMARY KEY (NV_MA, CLV_MA),
	CONSTRAINT FK_NHANVIEN FOREIGN KEY (NV_MA) REFERENCES dbo.NHANVIEN(NV_MA),
	CONSTRAINT FK_CALAMVIEC FOREIGN KEY (CLV_MA) REFERENCES dbo.CALAMVIEC(CLV_MA)
);
GO 

CREATE TABLE HOADON (
	HD_MA INT IDENTITY(1,1) PRIMARY KEY,
	HD_NGAYLAP DATETIME NOT NULL,
	HD_TONGTIEN MONEY,
	HD_HINHTHUCTHANHTOAN NVARCHAR(100)
);
GO

CREATE TABLE THUCPHAM (
	TP_MA INT PRIMARY KEY IDENTITY(1,1),
	TP_TEN NVARCHAR(100) NOT NULL,
	TP_LOAI NVARCHAR(100) NOT NULL,
	TP_GIA MONEY
);
GO

CREATE TABLE CHITIETHOADON (
	HD_MA INT,
	TP_MA INT,
	CTDH_SOLUONG INT,
	CTDH_MA_DONGIA MONEY,
	CONSTRAINT PK_CHITIETDONHANG PRIMARY KEY (HD_MA,TP_MA),
	CONSTRAINT FK_THUCPHAM_CHITIET FOREIGN KEY (TP_MA) REFERENCES dbo.THUCPHAM(TP_MA),
	CONSTRAINT FK_DONHANG_CHITIET FOREIGN KEY (HD_MA) REFERENCES dbo.HOADON(HD_MA)
);
GO

CREATE TABLE THUC_AN_QUA_NAU(
	TP_MA INT PRIMARY KEY,
	TP_TEN NVARCHAR(100) NOT NULL,
	TP_LOAI NVARCHAR(100) NOT NULL,
	TP_GIA MONEY,
	TAQN_SOLUONGCONLAI INT,
	TAQN_SOLUONGNAU INT,
	CONSTRAINT FK_THUCPHAN_TAQN FOREIGN KEY (TP_MA) REFERENCES dbo.THUCPHAM(TP_MA)
);
GO

CREATE TABLE MATHANG(
	TP_MA INT PRIMARY KEY,
	TP_TEN NVARCHAR(100) NOT NULL,
	TP_LOAI NVARCHAR(100) NOT NULL,
	TP_GIA MONEY,
	MH_SOLUONGTON INT,
	MH_GIATIENNHAP MONEY,
	MH_NGAYSX DATETIME,
	MH_HSD DATE,
	MH_NHACUNGCAP NVARCHAR(100),
	CONSTRAINT FK_THUCPHAM_MH FOREIGN KEY (TP_MA) REFERENCES dbo.THUCPHAM(TP_MA)
);
GO

CREATE TABLE DONNHAPHANG (
	DNH_MA INT PRIMARY KEY IDENTITY(1,1),
	DNH_NGAYDAT DATETIME,
	DNH_TONGTIEN MONEY,
);
GO 

CREATE TABLE CHITIETDONNHAPHANG (
	DNH_MA INT,
	TP_MA INT,
	CTDNH_SOLUONG INT,
	CTDNH_DONGIA MONEY,
	CONSTRAINT PK_CTDNH PRIMARY KEY (DNH_MA,TP_MA),
	CONSTRAINT FK_CTDNH_MH FOREIGN KEY (TP_MA) REFERENCES dbo.MATHANG(TP_MA),
	CONSTRAINT FK_CTDNH_DNH FOREIGN KEY (DNH_MA) REFERENCES dbo.DONNHAPHANG(DNH_MA)
);
GO

CREATE TABLE KHACHHANG
(
    KH_ID INT IDENTITY(1,1) PRIMARY KEY,
	KH_MSSV CHAR(20) UNIQUE,
	KH_SDT CHAR(20),
	KH_EMAIL NVARCHAR(100),
	CONSTRAINT KH_CHECK CHECK (LEN(KH_MSSV) < 20 AND LEN(KH_SDT) < 20 AND LEN(KH_EMAIL) < 100)
)
GO

CREATE
--DROP
TABLE GIOHANG(
	ID INT IDENTITY(1,1),
	KH_MA INT,
	TP_MA INT,
	GH_SOLUONG INT,
	GH_TONGTIEN MONEY,
	CONSTRAINT PK_GH PRIMARY KEY (ID,KH_MA, TP_MA),
	CONSTRAINT FK_GH_TP FOREIGN KEY (TP_MA) REFERENCES dbo.THUCPHAM(TP_MA)
)
GO 

CREATE
--DROP
TABLE TAIKHOAN
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
    UNAME CHAR(100) UNIQUE,
	PWD CHAR(100),
	LOAITK CHAR(100),
	MA INT UNIQUE,
	CONSTRAINT TK_cHECK CHECK (LOAITK = 'NHANVIEN' OR LOAITK = 'ADMIN' OR LOAITK = 'KHACHHANG')
)
GO


--------------------
CREATE 
--ALTER
PROC sp_themTaiKhoan
	@UN CHAR(100),
	@PW CHAR(100),
	@MSSV CHAR(20),
	@SDT CHAR(20),
	@EMAIL NVARCHAR(100)
AS
BEGIN TRANSACTION 
	BEGIN TRY
		IF(@UN IS NULL AND @PW IS NULL AND @MSSV IS NULL AND @SDT IS NULL AND @EMAIL IS NULL)
		BEGIN
		    PRINT 'THONG TIN KHONG HOP LE'
			ROLLBACK
			RETURN
		END
		INSERT INTO dbo.KHACHHANG
		(
		    KH_MSSV,
		    KH_SDT,
		    KH_EMAIL
		)
		VALUES
		(   @MSSV, -- KH_MSSV - char(20)
		    @SDT, -- KH_SDT - char(20)
		    @EMAIL  -- KH_EMAIL - nvarchar(100)
		    )

		DECLARE @ID_KH INT
		SELECT @ID_KH = KH_ID FROM dbo.KHACHHANG WHERE @MSSV = KH_MSSV
		INSERT INTO dbo.TAIKHOAN
		(
		    UNAME,
		    PWD,
		    LOAITK,
		    MA
		)
		VALUES
		(   @UN, -- UNAME - char(100)
		    @PW, -- PWD - char(100)
		    'KHACHHANG', -- LOAITK - char(100)
		    @ID_KH  -- MA - int
		    )
	END TRY
	BEGIN CATCH
		PRINT 'THEM TAI KHOAN KHONG THANH CONG'
		ROLLBACK
		RETURN
	END CATCH
COMMIT TRANSACTION
GO

-- XU LY DANG NHAP
CREATE
--alter
PROC sp_xulyDangNhap 
	@UN CHAR(100),
	@PW CHAR(100)
AS
BEGIN TRANSACTION 
	BEGIN TRY
		IF NOT EXISTS(SELECT * FROM dbo.TAIKHOAN WHERE UNAME = @UN)
		BEGIN
			ROLLBACK
			RETURN
		END
		IF NOT EXISTS(SELECT * FROM dbo.TAIKHOAN WHERE UNAME = @UN AND PWD= @PW)
		BEGIN
			ROLLBACK
			RETURN
		END
		SELECT * FROM dbo.TAIKHOAN WHERE UNAME = @UN AND PWD= @PW
	END TRY
	BEGIN CATCH
		ROLLBACK
		RETURN
	END CATCH
COMMIT TRANSACTION
GO


UPDATE dbo.GIOHANG SET GH_SOLUONG = GH_SOLUONG WHERE TP_MA = TP_MA AND KH_MA = KH_MA

SELECT TP.TP_TEN, TP.TP_LOAI, GH.GH_SOLUONG, GH.GH_TONGTIEN FROM dbo.GIOHANG GH, dbo.THUCPHAM TP WHERE GH.TP_MA = TP.TP_MA 
------------------------------------------------------

INSERT INTO dbo.THUCPHAM
(
    TP_TEN,
    TP_LOAI,
    TP_GIA
)
VALUES
(   N'Sting', -- TP_TEN - nvarchar(100)
    N'Đồ ăn liền', -- TP_LOAI - nvarchar(100)
    10000 -- TP_GIA - money
    )

INSERT INTO dbo.MATHANG
(
    TP_MA,
    TP_TEN,
    TP_LOAI,
    TP_GIA,
    MH_SOLUONGTON,
    MH_GIATIENNHAP,
    MH_NGAYSX,
    MH_HSD,
    MH_NHACUNGCAP
)
VALUES
(   1,    -- TP_MA - int
    N'Sting', -- TP_TEN - nvarchar(100)
    N'Đồ ăn liền', -- TP_LOAI - nvarchar(100)
    10000, -- TP_GIA - money
    100, -- MH_SOLUONGTON - int
    5000, -- MH_GIATIENNHAP - money
    '10/05/2022', -- MH_NGAYSX - datetime
    '10/5/2023', -- MH_HSD - date
    NULL  -- MH_NHACUNGCAP - nvarchar(100)
    )

INSERT INTO dbo.THUCPHAM
(
    TP_TEN,
    TP_LOAI,
    TP_GIA
)
VALUES
(   N'Phở', -- TP_TEN - nvarchar(100)
    N'Đồ nấu', -- TP_LOAI - nvarchar(100)
    30000 -- TP_GIA - money
)

INSERT INTO dbo.THUC_AN_QUA_NAU
(
    TP_MA,
    TP_TEN,
    TP_LOAI,
    TP_GIA,
    TAQN_SOLUONGCONLAI,
    TAQN_SOLUONGNAU
)
VALUES
(   2,    -- TP_MA - int
    N'Phở', -- TP_TEN - nvarchar(100)
    N'Đồ nấu', -- TP_LOAI - nvarchar(100)
    30000, -- TP_GIA - money
    30, -- TAQN_SOLUONGCONLAI - int
    100  -- TAQN_SOLUONGNAU - int
    )
INSERT INTO dbo.HOADON
(
    HD_NGAYLAP,
    HD_TONGTIEN,
    HD_HINHTHUCTHANHTOAN
)
VALUES
(   GETDATE(), -- HD_NGAYLAP - datetime
    10000,      -- HD_TONGTIEN - money
    N'Trực tiêp'       -- HD_HINHTHUCTHANHTOAN - nvarchar(100)
    )

INSERT INTO dbo.CHITIETHOADON
(
    HD_MA,
    TP_MA,
    CTDH_SOLUONG,
    CTDH_MA_DONGIA
)
VALUES
(   1,    -- HD_MA - int
    1,    -- TP_MA - int
    4, -- CTDH_SOLUONG - int
    40000 -- CTDH_MA_DONGIA - money
)

INSERT INTO dbo.CHITIETHOADON
(
    HD_MA,
    TP_MA,
    CTDH_SOLUONG,
    CTDH_MA_DONGIA
)
VALUES
(   1,    -- HD_MA - int
    2,    -- TP_MA - int
    2, -- CTDH_SOLUONG - int
    60000 -- CTDH_MA_DONGIA - money
)

INSERT INTO dbo.DONNHAPHANG
(
    DNH_NGAYDAT,
    DNH_TONGTIEN
)
VALUES
(   GETDATE(), -- DNH_NGAYDAT - datetime
    NULL  -- DNH_TONGTIEN - money
    )

INSERT INTO dbo.CHITIETDONNHAPHANG
(
    DNH_MA,
    TP_MA,
    CTDNH_SOLUONG,
    CTDNH_DONGIA
)
VALUES
(   1,    -- DNH_MA - int
    1,    -- TP_MA - int
    100, -- CTDNH_SOLUONG - int
    500000  -- CTDNH_DONGIA - money
    )

INSERT INTO dbo.NHANVIEN
(
    NV_TEN,
    NV_GIOTINH,
    NV_SDT,
    NV_LUONG_GIO
)
VALUES
(   N'CHÁN VĂN NẢN', -- NV_TEN - nvarchar(100)
    N'Nam', -- NV_GIOTINH - nvarchar(10)
    N'0123456789', -- NV_SDT - nvarchar(20)
    20000 -- NV_LUONG_GIO - money
    )


INSERT INTO dbo.CALAMVIEC
(
    CLV_NGAY,
    CLV_GIOBATDAU,
    CLV_GIOKETTHUC
)
VALUES
(   GETDATE(), -- CLV_NGAY - date
    '07:00:00', -- CLV_GIOBATDAU - time
    '13:00:00'  -- CLV_GIOKETTHUC - time
    )

INSERT INTO dbo.PHANCONGLAMVIEC
(
    CLV_MA,
    NV_MA
)
VALUES
(   1, -- CLV_MA - int
    1  -- NV_MA - int
    )


