CREATE
--DROP
DATABASE DA_NMCNPM
GO

USE DA_NMCNPM 
GO

CREATE TABLE NHANVIEN (
	NV_MA INT IDENTITY(1,1) PRIMARY KEY,
	NV_TEN NVARCHAR(100) NOT NULL,
	NV_LUONG_GIO MONEY,
);
GO

CREATE TABLE CALAMVIEC (
	CLV_MA INT IDENTITY(1,1) PRIMARY KEY,
	CLV_NGAY DATE,
	CLV_GIOBATDAU TIME,
	CLV_GIOKETTHUC TIME
)
GO

CREATE TABLE PHANCONGLAMVIEC(
	CLV_MA INT,
	NV_MA INT,
	CONSTRAINT PK_PHANCONGLAMVIEC PRIMARY KEY (NV_MA, CLV_MA),
	CONSTRAINT FK_NHANVIEN FOREIGN KEY (NV_MA) REFERENCES dbo.NHANVIEN(NV_MA),
	CONSTRAINT FK_CALAMVIEC FOREIGN KEY (CLV_MA) REFERENCES dbo.CALAMVIEC(CLV_MA)
);
GO 

CREATE TABLE HOADON (
	HD_MA INT IDENTITY(1,1) PRIMARY KEY,
	HD_NGAYLAP DATETIME NOT NULL,
	HD_TONGTIEN MONEY,
	HD_HINHTHUCTHANHTOAN NVARCHAR(100)
);
GO

CREATE TABLE THUCPHAM (
	TP_MA INT PRIMARY KEY IDENTITY(1,1),
	TP_TEN NVARCHAR(100) NOT NULL,
	TP_LOAI NVARCHAR(100) NOT NULL,
	TP_GIA MONEY
);
GO

CREATE TABLE CHITIETHOADON (
	HD_MA INT,
	TP_MA INT,
	CTDH_SOLUONG INT,
	CTDH_MA_DONGIA MONEY,
	CONSTRAINT PK_CHITIETDONHANG PRIMARY KEY (HD_MA,TP_MA),
	CONSTRAINT FK_THUCPHAM_CHITIET FOREIGN KEY (TP_MA) REFERENCES dbo.THUCPHAM(TP_MA),
	CONSTRAINT FK_DONHANG_CHITIET FOREIGN KEY (HD_MA) REFERENCES dbo.HOADON(HD_MA)
);
GO

CREATE TABLE THUC_AN_QUA_NAU(
	TP_MA INT PRIMARY KEY,
	TP_TEN NVARCHAR(100) NOT NULL,
	TP_LOAI NVARCHAR(100) NOT NULL,
	TP_GIA MONEY,
	TAQN_SOLUONGCONLAI INT,
	TAQN_SOLUONGNAU INT,
	CONSTRAINT FK_THUCPHAN_TAQN FOREIGN KEY (TP_MA) REFERENCES dbo.THUCPHAM(TP_MA)
);
GO

CREATE TABLE MATHANG(
	TP_MA INT PRIMARY KEY,
	TP_TEN NVARCHAR(100) NOT NULL,
	TP_LOAI NVARCHAR(100) NOT NULL,
	TP_GIA MONEY,
	MH_SOLUONGTON INT,
	MH_GIATIENNHAP MONEY,
	MH_NGAYSX DATETIME,
	MH_HSD DATE,
	MH_NHACUNGCAP NVARCHAR(100),
	CONSTRAINT FK_THUCPHAM_MH FOREIGN KEY (TP_MA) REFERENCES dbo.THUCPHAM(TP_MA)
);
GO

CREATE TABLE DONNHAPHANG (
	DNH_MA INT PRIMARY KEY IDENTITY(1,1),
	DNH_NGAYDAT DATETIME,
	DNH_TONGTIEN MONEY,
);
GO 

CREATE TABLE CHITIETDONNHAPHANG (
	DNH_MA INT,
	TP_MA INT,
	CTDNH_SOLUONG INT,
	CTDNH_DONGIA MONEY,
	CONSTRAINT PK_CTDNH PRIMARY KEY (DNH_MA,TP_MA),
	CONSTRAINT FK_CTDNH_MH FOREIGN KEY (TP_MA) REFERENCES dbo.MATHANG(TP_MA),
	CONSTRAINT FK_CTDNH_DNH FOREIGN KEY (DNH_MA) REFERENCES dbo.DONNHAPHANG(DNH_MA)
);
GO

CREATE TABLE GIOHANG(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TP_MA INT,
	GH_SOLUONG INT,
	GH_TONGTIEN MONEY
	CONSTRAINT FK_GH_TP FOREIGN KEY (TP_MA) REFERENCES dbo.THUCPHAM(TP_MA)
)
GO 


INSERT INTO dbo.THUCPHAM
(
    TP_TEN,
    TP_LOAI,
    TP_GIA
)
VALUES
(   N'Sting', -- TP_TEN - nvarchar(100)
    N'Đồ ăn liền', -- TP_LOAI - nvarchar(100)
    10000 -- TP_GIA - money
    )

INSERT INTO dbo.MATHANG
(
    TP_MA,
    TP_TEN,
    TP_LOAI,
    TP_GIA,
    MH_SOLUONGTON,
    MH_GIATIENNHAP,
    MH_NGAYSX,
    MH_HSD,
    MH_NHACUNGCAP
)
VALUES
(   1,    -- TP_MA - int
    N'Sting', -- TP_TEN - nvarchar(100)
    N'Đồ ăn liền', -- TP_LOAI - nvarchar(100)
    10000, -- TP_GIA - money
    100, -- MH_SOLUONGTON - int
    5000, -- MH_GIATIENNHAP - money
    '10/05/2022', -- MH_NGAYSX - datetime
    '10/5/2023', -- MH_HSD - date
    NULL  -- MH_NHACUNGCAP - nvarchar(100)
    )

INSERT INTO dbo.THUCPHAM
(
    TP_TEN,
    TP_LOAI,
    TP_GIA
)
VALUES
(   N'Phở', -- TP_TEN - nvarchar(100)
    N'Đồ nấu', -- TP_LOAI - nvarchar(100)
    30000 -- TP_GIA - money
)

INSERT INTO dbo.THUC_AN_QUA_NAU
(
    TP_MA,
    TP_TEN,
    TP_LOAI,
    TP_GIA,
    TAQN_SOLUONGCONLAI,
    TAQN_SOLUONGNAU
)
VALUES
(   2,    -- TP_MA - int
    N'Phở', -- TP_TEN - nvarchar(100)
    N'Đồ nấu', -- TP_LOAI - nvarchar(100)
    30000, -- TP_GIA - money
    30, -- TAQN_SOLUONGCONLAI - int
    100  -- TAQN_SOLUONGNAU - int
    )
INSERT INTO dbo.HOADON
(
    HD_NGAYLAP,
    HD_TONGTIEN,
    HD_HINHTHUCTHANHTOAN
)
VALUES
(   GETDATE(), -- HD_NGAYLAP - datetime
    10000,      -- HD_TONGTIEN - money
    N'Trực tiêp'       -- HD_HINHTHUCTHANHTOAN - nvarchar(100)
    )

INSERT INTO dbo.CHITIETHOADON
(
    HD_MA,
    TP_MA,
    CTDH_SOLUONG,
    CTDH_MA_DONGIA
)
VALUES
(   1,    -- HD_MA - int
    1,    -- TP_MA - int
    4, -- CTDH_SOLUONG - int
    40000 -- CTDH_MA_DONGIA - money
)

INSERT INTO dbo.CHITIETHOADON
(
    HD_MA,
    TP_MA,
    CTDH_SOLUONG,
    CTDH_MA_DONGIA
)
VALUES
(   1,    -- HD_MA - int
    2,    -- TP_MA - int
    2, -- CTDH_SOLUONG - int
    60000 -- CTDH_MA_DONGIA - money
)

INSERT INTO dbo.DONNHAPHANG
(
    DNH_NGAYDAT,
    DNH_TONGTIEN
)
VALUES
(   GETDATE(), -- DNH_NGAYDAT - datetime
    NULL  -- DNH_TONGTIEN - money
    )

INSERT INTO dbo.CHITIETDONNHAPHANG
(
    DNH_MA,
    TP_MA,
    CTDNH_SOLUONG,
    CTDNH_DONGIA
)
VALUES
(   1,    -- DNH_MA - int
    1,    -- TP_MA - int
    100, -- CTDNH_SOLUONG - int
    500000  -- CTDNH_DONGIA - money
    )

INSERT dbo.NHANVIEN
(
    NV_TEN,
    NV_LUONG_GIO
)
VALUES
(   N'Chán Văn Nản', -- NV_TEN - nvarchar(100)
    25000 -- NV_LUONG_GIO - money
    )

INSERT INTO dbo.CALAMVIEC
(
    CLV_NGAY,
    CLV_GIOBATDAU,
    CLV_GIOKETTHUC
)
VALUES
(   GETDATE(), -- CLV_NGAY - date
    '07:00:00', -- CLV_GIOBATDAU - time
    '13:00:00'  -- CLV_GIOKETTHUC - time
    )

INSERT INTO dbo.PHANCONGLAMVIEC
(
    CLV_MA,
    NV_MA
)
VALUES
(   1, -- CLV_MA - int
    1  -- NV_MA - int
    )